true_bool: True
false_bool: False


nodenorm_params:
  base_url: https://nodenormalization-sri.renci.org/1.5/
  query: get_normalized_nodes
  params:
    conflate: True
    drug_chemical_conflate: True
    description: False
    individual_types: False

name_resolver_params:
  url: https://name-resolution-sri.renci.org/
  service: lookup
  autocomplete_setting: true
  id_limit: 10
  offset: 0

orangebook_zip: https://www.fda.gov/media/76860/download?attachment

standardization_mapping_ob:
  Ingredient: source_ingredients
  Approval_Date: approval_date
  Type: marketing_status_usa

standardization_mapping_ema:
  International non-proprietary name (INN) / common name: source_ingredients
  Marketing authorisation date: approval_date
  ATC code (human): atc_code

standardization_mapping_pmda:
  "Active Ingredient (underlined: new active ingredient)": source_ingredients
  Approval Date: approval_date

standardization_mapping_purple_book:
  "Proper Name": source_ingredients
  Approval Date: approval_date
  Marketing Status: marketing_status_usa


deduplication_columns_usa:
  - source_ingredients
  - approval_date
  - marketing_status_usa

deduplication_columns:
  - source_ingredients
  - approval_date

approval_tags:
  usa: approved_usa
  eur: approved_europe
  jpn: approved_japan

enrichment_tags:
  steroid:
    input_col: label
    output_col: is_steroid
    model_params: 
      model: gpt-4o-mini
      prompt: Is this drug a corticosteroid drug? Return TRUE or FALSE only.
      temperature: 0.2
  antibiotic:
    input_col: label
    output_col: is_antimicrobial
    model_params:
      model: gpt-4o
      prompt: "Are any of these drugs in any of the following drug classes: an antibiotic drug, an antiviral drug (usually end in '-vir' or '-udine'), an antiretroviral drug, an antiparasitic drug, or an antifungal drug? Return TRUE or FALSE only."
      temperature: 0.2
  chemotherapy:
    input_col: label
    output_col: is_chemotherapy
    model_params:
      model: gpt-4o-mini
      prompt: Is this drug a cytotoxic chemotherapy drug used to treat cancer? Return TRUE or FALSE only.
      temperature: 0.2
  glucose_regulator:
    input_col: label
    output_col: is_glucose_regulator
    model_params:
      model: gpt-4o-mini
      prompt: Is this drug a drug which is primarily used to regulate glucose levels? Return TRUE or FALSE only.
      temperature: 0.2
  vaccine_or_antigen:
    input_col: label
    output_col: is_vaccine_or_antigen
    model_params:
      model: gpt-4o-mini
      prompt: Is this drug a vaccine or antigen? Return TRUE or FALSE only.
      temperature: 0.2
  no_therapeutic_value:
    input_col: label
    output_col: is_no_therapeutic_value
    model_params:
      model: gpt-4o
      prompt: Could this drug be classified as having little potential therapeutic value? For example, sterile water, tryptan blue, copper, and soybean oil are considered low potential therapeutic value. Unusual drugs may still have therapeutic value - do not discount drugs just because they are not approve in the USA or Europe. Return TRUE or FALSE only.
      temperature: 0.2
  metallic_salt:
    input_col: label
    output_col: is_metallic_salt
    model_params:
      model: gpt-4o
      prompt: Is this drug a simple metallic salt? Return TRUE or FALSE only.
      temperature: 0.2
  allergen:
    input_col: label
    output_col: is_allergen
    model_params:
      model: gpt-4o
      prompt: Would this drug primarily used as an allergen for allergy testing? Return TRUE or FALSE only.
      temperature: 0.2
  diagnostic_or_radioisotope:
    input_col: label
    output_col: is_radioisotope_or_diagnostic_agent
    model_params:
      model: gpt-4o
      prompt: Is this drug primarily used as a radiolabel or diagnostic agent? Return TRUE or FALSE only.
      temperature: 0.2
  cancer_drug:
    input_col: label
    output_col: is_cancer_drug
    model_params:
      model: gpt-4o
      prompt: Is this drug used as a primary treatment for cancer or in conjunction with cancer therapy? Return TRUE or FALSE only.
      temperature: 0.2

combo_therapy_tags:      
  combination_therapy_tag_drug:
    input_col: source_ingredients
    output_col: is_combination_therapy
    model_params:
      model: gpt-4.1
      prompt: "Is the following a representation of a coformulated drug or combination therapy? If it is two salts of the same active moiety, do not consider it to be a combination therapy. Return TRUE or FALSE only. DRUG:"
      temperature: 0
  combination_therapy_split_drug:
    input_col: source_ingredients
    output_col: combination_therapy_ingredients
    model_params:
      model: gpt-4.1
      prompt: "Please split the drug name into a structured list of drugs eg 'drug1|drug2|drug3|...|drugN'. and return ONLY the list. DRUG:"
      temperature: 0
  
component_ids_colname: ingredient_ids

id_correct_incorrect_tag_drug:
  model_params:
    model: gpt-4o
    prompt: "Are the following concepts similar enough that they could be considered the same drug? Return only TRUE or FALSE. Provide no explanation."
    temperature: 0

llm_best_id_tag_drug:
  model_params:
    model: gpt-4o
    prompt: "Return ONLY the best ontological ID (e.g., 'PUBCHEM:00000001') from the following to represent the provided drug concept. Do not include the label or item number. If no matches, return NONE."
    temperature: 0


date_reformatting_tag:      
  params:
    input_col: source_ingredients
    output_col: reformatted_date_tag
    model_params:
      model: gpt-4.1
      prompt: "Is the following a representation of a coformulated drug or combination therapy? If it is two salts of the same active moiety, do not consider it to be a combination therapy. Return TRUE or FALSE only. DRUG:"
      temperature: 0