true_bool: True
false_bool: False

nodenorm_params:
  base_url: https://nodenormalization-sri.renci.org/1.5/
  query: get_normalized_nodes
  params:
    conflate: True
    drug_chemical_conflate: True
    description: False
    individual_types: False

name_resolver_params:
  url: https://name-resolution-sri.renci.org/
  service: lookup
  autocomplete_setting: true
  id_limit: 10
  offset: 0
  timeout: 5

name_resolver_params_llm_improve:
  url: https://name-resolution-sri.renci.org/
  service: lookup
  autocomplete_setting: true
  id_limit: 30
  offset: 0
  timeout: 30

orangebook_zip: https://www.fda.gov/media/76860/download?attachment

standardization_mapping_general:
  ingredients: source_ingredients
  approval_date: approval_date

standardization_mapping_ob:
  Ingredient: source_ingredients
  Approval_Date: approval_date
  Type: marketing_status_usa

standardization_mapping_ema:
  International non-proprietary name (INN) / common name: source_ingredients
  Marketing authorisation date: approval_date
  ATC code (human): atc_code
  Therapeutic indication: indication

standardization_mapping_pmda:
  "Active Ingredient (underlined: new active ingredient)": source_ingredients
  Approval Date: approval_date
  Indications: indication

standardization_mapping_india:
  Drug Name: source_ingredients
  Date of Approval: approval_date
  Indication: indication

standardization_mapping_purple_book:
  "Proper Name": source_ingredients
  Approval Date: approval_date
  Marketing Status: marketing_status_usa

standardization_mapping_russia:
  International non -parted or chemical name: source_ingredients
  The date of registration: approval_date

final_list_remap:
  corrected_curie_norm: curie
  corrected_curie_norm_label: label
  source_ingredients: source_ingredients
  approved_usa: approved_usa
  marketing_status_usa: marketing_status_usa
  approved_europe: approved_europe
  approved_japan: approved_japan
  approved_india: approved_india
  approved_russia: approved_russia
  is_combination_therapy: is_combination_therapy
  combination_therapy_ingredients: combination_therapy_ingredients
  combination_therapy_ingredients_curies: combination_therapy_ingredients_curies
  is_steroid: is_steroid
  is_antimicrobial: is_antimicrobial
  is_chemotherapy: is_chemotherapy
  is_glucose_regulator: is_glucose_regulator
  is_vaccine_or_antigen: is_vaccine_or_antigen
  is_no_therapeutic_value: is_no_therapeutic_value
  is_metallic_salt: is_metallic_salt
  is_allergen: is_allergen
  is_radioisotope_or_diagnostic_agent: is_radioisotope_or_diagnostic_agent
  is_cancer_drug: is_cancer_drug
  alternate_ids: alternate_ids
  atc_codes: atc_codes
  atc_main: atc_main
  atc_level1: atc_level1
  atc_level2: atc_level2
  atc_level3: atc_level3
  atc_level4: atc_level4
  atc_level5: atc_level5
  smiles: smiles

deduplication_columns_usa:
  - source_ingredients
  - approval_date
  - marketing_status_usa

deduplication_columns:
  - source_ingredients

approval_tags:
  usa: approved_usa
  eur: approved_europe
  jpn: approved_japan
  rus: approved_russia
  ind: approved_india

source_ingredients_column: source_ingredients

label_column: corrected_curie_norm_label
enrichment_tags:
  steroid:
    output_col: is_steroid
    model_params: 
      model: gpt-4o
      prompt: Is this drug a corticosteroid drug? Return TRUE or FALSE only.
      temperature: 0
  antibiotic:
    output_col: is_antimicrobial
    model_params:
      model: gpt-4o
      prompt: "Are any of these drugs in any of the following drug classes: an antibiotic drug, an antiviral drug (usually end in '-vir' or '-udine'), an antiretroviral drug, an antiparasitic drug, or an antifungal drug? Return TRUE or FALSE only."
      temperature: 0
  chemotherapy:
    output_col: is_chemotherapy
    model_params:
      model: gpt-4o
      prompt: Is this drug a cytotoxic chemotherapy drug used to treat cancer? Return TRUE or FALSE only.
      temperature: 0
  glucose_regulator:
    output_col: is_glucose_regulator
    model_params:
      model: gpt-4o
      prompt: Is this drug a drug which is primarily used to regulate glucose levels? Return TRUE or FALSE only.
      temperature: 0
  vaccine_or_antigen:
    output_col: is_vaccine_or_antigen
    model_params:
      model: gpt-4o
      prompt: Is this drug a vaccine or antigen? Return TRUE or FALSE only.
      temperature: 0
  no_therapeutic_value:
    output_col: is_no_therapeutic_value
    model_params:
      model: gpt-4o
      prompt: Could this drug be classified as having little potential therapeutic value? For example, sterile water, tryptan blue, copper, and soybean oil are considered low potential therapeutic value. Unusual drugs may still have therapeutic value - do not discount drugs just because they are not approve in the USA or Europe. Return TRUE or FALSE only.
      temperature: 0
  metallic_salt:
    output_col: is_metallic_salt
    model_params:
      model: gpt-4o
      prompt: Is this drug a simple metallic salt? Return TRUE or FALSE only for the whole drug. If multiple simple metallic salts are provided, return TRUE. If anything other than a simple metallic salt is provided in the description, return FALSE.
      temperature: 0
  allergen:
    output_col: is_allergen
    model_params:
      model: gpt-4o
      prompt: Would this drug primarily used as an allergen for allergy testing? Return TRUE or FALSE only.
      temperature: 0
  diagnostic_or_radioisotope:
    output_col: is_radioisotope_or_diagnostic_agent
    model_params:
      model: gpt-4o
      prompt: Is this drug primarily used as a radiolabel or diagnostic agent? Return TRUE or FALSE only.
      temperature: 0
  cancer_drug:
    output_col: is_cancer_drug
    model_params:
      model: gpt-4o
      prompt: Is this drug used as a primary treatment for cancer or in conjunction with cancer therapy? Return TRUE or FALSE only.
      temperature: 0

combo_therapy_tags:      
  combination_therapy_tag_drug:
    input_col: source_ingredients
    output_col: is_combination_therapy
    model_params:
      model: gpt-4o-mini
      prompt: "Is the following a representation of a coformulated drug or combination therapy? If it is two salts of the same active moiety, do not consider it to be a combination therapy. Return TRUE or FALSE only. DRUG:"
      temperature: 0
  
combination_therapy_split_drug:
  input_col: source_ingredients
  output_col: combination_therapy_ingredients
  model_params:
    model: gpt-4o
    prompt: "Please split the drug name that follows this prompt into a structured list of drugs separated by vertical pipes \"|\", e.g., 'drug1|drug2|drug3|...|drugN'. Return ONLY the list. If only one ingredient, return an empty response. If a multi-component drug (e.g. \"Meningococcal groups A, B, C vaccine\", return each item with its full name so that it could be parsed independently, e.g. \"Meningococcal group A vaccine | Meningococcal group B vaccine | Meningococcal group C vaccine \". If the contents are proprietary or otherwise represent a violaiton of openai policies, please return the original drug name only. DRUG NAME:"
    temperature: 0

id_correct_incorrect_tag:
  params:
    input_col: llm_qc_comparison_col
    output_col: id_correct
    model_params:
      model: gpt-4o
      prompt: "Are the following concepts similar enough that they could be considered the same drug? Return only TRUE or FALSE. Provide no explanation. Drugs that contain the same set of active moieties can be considered to be the same drug, e.g., fentanyl and fentanyl citrate can be considered equivalent for this evaluation."
      temperature: 0


llm_best_id_tag_drug_prompt: "Return ONLY the best ontological ID (e.g., 'PUBCHEM:00000001') from the following to represent the provided drug concept. Do not include the label or item number. If no matches, return NONE. If multiple matches, return the simplest one that contains all active moieties, e.g., if fentanyl citrate is provided and the options are [fentanyl citrate, fentanyl hydrochloride, fentanyl citrate injection, fentanyl], pick fentanyl"


date_reformatting_tag:      
  params:
    input_col: approval_date
    output_col: approval_date
    model_params:
      model: gpt-4o-mini
      prompt: "Please reformat the following drug approval date to YYYYMMDD format. Return only the reformatted date in YYYYMMDD format. If just a year is provided, return January 1 of that year, e.g. 1976->19760101. If inadequate information is provided to determine the year, return all X, e.g., XXXXXXXX. DATE: "
      temperature: 0


best_id_column: corrected_curie









###########################################################################################
################################################# ON LABEL ################################
###########################################################################################
###########################################################################################
###########################################################################################

path_to_fda_labels: /Volumes/MML/2025_06_30_dailymed/

column_names:
  source_file_column: "source file"
  indications_active_ingredients: "active ingredient"
  indications_text_column: "indications text"
  indications_structured_list_column: "structured list"
  disease_name_column: "disease name"
  drug_name_column: "drug name"
  drug_id_column: "drug id nameres"
  drug_label_column: "drug label nameres"
  disease_id_column: "disease id nameres"
  disease_label_column: "disease label nameres"
  llm_true_false_column_disease: "llm_nameres_correct"
  nameres_options_id_column: "nameres id options disease"
  nameres_options_label_column: "nameres label options disease"
  llm_improved_id_column : "llm disease id"
  llm_normalized_id_column_disease: "final normalized disease id"
  llm_normalized_label_column_disease: "final normalized disease label"
  llm_true_false_column_drug: "llm_nameres_correct_drug"
  llm_improved_id_column_drug: "llm drug id"
  llm_normalized_id_column_drug: "final normalized drug id"
  llm_normalized_label_column_drug: "final normalized drug label"
  deduplication_column: "drug|disease"
  downfilled_true_false_column: "downfilled from mondo"
  contraindications_structured_list_column: "diseases contraindicated"
  contraindications_text_column: "contraindications"
  contraindications_active_ingredients: "active ingredient"
  new_contraindications_disease_name_column: "disease contraindicated"
  is_allergen_column: "is_allergen"
  is_diagnostic_column: "is_diagnostic_agent"


pmda_mapping_columns:
  origin_string: "Active Ingredient (underlined: new active ingredient)"
  id: curie
  label: curie_label
  Indications: indications

ema_mapping_columns:
  origin_string: "Active substance"
  id: curie
  label: curie_label
  Therapeutic indication: indication

biolink_type_disease: "DiseaseOrPhenotypicFeature"
biolink_type_drug: "ChemicalOrDrugOrTreatment"

indications_structured_list_prompt: "Produce a list of diseases treated in the following therapeutic indications text. Please format the list as: 'item1|item2|...|itemN'. Do not include any other text in the response. If no diseases are treated, return 'None'. If the drug is only used for imaging, diagnostic, allergy testing, or procedural purposes (e.g., Technetium), return 'non-therapeutic'. Do not infer any diseases - only list diseases directly included in the passage. Be as specific as possible when naming diseases. If no text is provided, respond 'None'. START TEXT HERE:"
contraindications_structured_list_prompt: "Produce a list of contraindicated diseases in the following contraindications text. Please format the list as: 'item1|item2|...|itemN'. Do not include any other text in the response. If no contraindications, return 'None'. Do not include drug hypersensitivity. Do not infer any diseases - only list diseases directly included in the passage. If no text is provided, respond 'None'. Do not include therapeutic indications if the input text contains indications. Do not include interaction contraindications, i.e., when a drug is used concurrently with another drug. Exclude conditions related to allergy, e.g. anaphylaxis, angioedema, urticaria.  START TEXT HERE:"

is_allergen_prompt: "Is the following active ingredient commonly used as an allergen for allergy testing? Respond only TRUE or FALSE. Provide no explanation. ACTIVE INGREDIENT: "
is_radiolabel_prompt: "Is the following active ingredient commonly used as a radiolabel or diagnostic agent? Respond only TRUE or FALSE. Provide no explanation. ACTIVE INGREDIENT: "

gemini_safety_setting: SafetySetting.HarmBlockThreshold.BLOCK_ONLY_HIGH

strings_to_clean_from_disease_list:
  - "LLM EXTRACTION ERROR"
  - "None "
  - "None"
  - ""
  - "none"
  - "ERROR"

cleaning_regex_sub_pattern: "[^A-Za-z0-9 ]+"

orchard_asset_field_names:
  drug_field_name: drug_kg_node_id
  disease_field_name: disease_kg_node_id
  indication_field_name: indication